- sku: UNKNOWN
  brand: Labor
  finish: UNKNOWN
  routing_tag: GENERAL
  oneclick_description: Outside Partner Painting / Patch Basic Patch & Paint Bathroom
    Walls & Ceiling (Does Not Include Doors & Door Casings) Includes Patching any
    wall damages from Demolition, as well as labor for Priming & Painting. Customer
    must supply paint and any applicable primer at time of installation. If Materials
    are available at time of installation customer is subject to a $150 trip surcharge.
  printable:
    description: Basic Patch & Paint Bathroom Walls & Ceiling
    finish: UNKNOWN
    dimensions: ''
  id: STG-87437618
